### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by DenisCarriere** [sleepycat/geox#4]
Added automatic coverage in your `travis.yml`.

Just need to add the repo to https://coveralls.io/

``` yml
language: node_js
node_js:
  - 6
notifications:
  email:
    - mike@korora.ca
after_success:
  - 'nyc report --reporter=text-lcov | coveralls'
```
